# Generated by Django 2.2 on 2021-05-25 08:03

import agenda.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('last_modified', models.DateField(auto_now=True)),
                ('tags', models.CharField(max_length=10)),
                ('public', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('notify_me', models.BooleanField(default=False)),
                ('notify_me_at', models.TimeField(blank=True, default=agenda.models.default_notify_time)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
