# Generated by Django 2.2 on 2021-05-14 13:10

import agenda.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='agenda_visibility',
            field=models.CharField(choices=[(1, 'public'), (2, 'private')], default='private', max_length=7),
        ),
        migrations.AddField(
            model_name='agenda',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 13, 10, 6, 348549, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='agenda',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='notify_me_at',
            field=models.DateTimeField(default=agenda.models.default_notify_time),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tags',
            field=models.CharField(default='Tag', max_length=10),
        ),
    ]
