# Generated by Django 2.2 on 2021-05-25 08:36

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='notify_me_at',
            field=models.TimeField(blank=True, default=agenda.models.default_notify_time, null=True),
        ),
    ]
