# Generated by Django 2.2 on 2021-05-14 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210514_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
