# Generated by Django 2.2 on 2021-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210525_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['entry_date']},
        ),
    ]
