# Generated by Django 2.2 on 2021-05-14 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20210514_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda_visibility',
            field=models.CharField(choices=[(1, 'private'), (2, 'public')], default='private', max_length=7),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='notify_me_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 21, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(default='My Agenda', max_length=100),
        ),
    ]
