# Generated by Django 2.2 on 2021-05-18 07:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0006_auto_20210517_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='notify_me_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 6, 0, tzinfo=utc)),
        ),
    ]
