# Generated by Django 2.2 on 2021-05-19 10:18

import agenda.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20210518_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='notify_me_at',
            field=models.TimeField(default=agenda.models.default_notify_time),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tags',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
