# Generated by Django 2.2 on 2021-05-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20210519_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='user',
            new_name='added_by',
        ),
    ]
