# Generated by Django 2.2 on 2021-05-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20210519_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='added_by',
            new_name='user',
        ),
    ]
